# Configuration for the differential drive controller of the robot.
car:
  diff_drive_controller:
    # Specifies the type of the controller used.
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50 # Rate at which the controller publishes its messages (in Hz).

    # Names of the joints for the left and right wheels.
    left_wheel: ['l_f_w_j','l_r_w_j']  # left front wheel joint, left rear wheel joint
    right_wheel: ['r_f_w_j','r_r_w_j']  # right front wheel joint, right rear wheel joint

    # Physical properties of the wheel assembly.
    wheel_separation: 1.2
    wheel_radius: 0.4

    # Odometry covariances for the encoder output of the robot.
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # covariance matrix for pose (position and orientation)
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]  # covariance matrix for twist (velocity and angular velocity)

    # The base frame identifier for the robot, used in transformations and localization.
    base_frame_id: chassis

    # Configurations for linear and angular velocity and acceleration limits.
    linear:
      x:
        has_velocity_limits    : false
        max_velocity           : 1000
        has_acceleration_limits: false
        max_acceleration       : 1000
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0
        has_acceleration_limits: true
        max_acceleration       : 0
